// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkxUIOwSaBwICA7o5ZaLAextPP_-Q3Czg',
    appId: '1:959958248558:web:8fb61dc1392af60d9a8a7f',
    messagingSenderId: '959958248558',
    projectId: 'speech-app-91373',
    authDomain: 'speech-app-91373.firebaseapp.com',
    storageBucket: 'speech-app-91373.firebasestorage.app',
    measurementId: 'G-NS8S63BFC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyb4XCHzZ_ak0MqL5JOgQAyHMHZ-QPvE0',
    appId: '1:959958248558:android:fc44cdf154f6e79d9a8a7f',
    messagingSenderId: '959958248558',
    projectId: 'speech-app-91373',
    storageBucket: 'speech-app-91373.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjHpKFN8a7-oVORbRzb9nmBN-vj_aExWY',
    appId: '1:959958248558:ios:7930933d745126a99a8a7f',
    messagingSenderId: '959958248558',
    projectId: 'speech-app-91373',
    storageBucket: 'speech-app-91373.firebasestorage.app',
    iosClientId: '959958248558-i170vogfr0qbvs02hpb1alsp8du46jni.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjHpKFN8a7-oVORbRzb9nmBN-vj_aExWY',
    appId: '1:959958248558:ios:7930933d745126a99a8a7f',
    messagingSenderId: '959958248558',
    projectId: 'speech-app-91373',
    storageBucket: 'speech-app-91373.firebasestorage.app',
    iosClientId: '959958248558-i170vogfr0qbvs02hpb1alsp8du46jni.apps.googleusercontent.com',
    iosBundleId: 'com.example.speechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkxUIOwSaBwICA7o5ZaLAextPP_-Q3Czg',
    appId: '1:959958248558:web:9856d3f56b3788179a8a7f',
    messagingSenderId: '959958248558',
    projectId: 'speech-app-91373',
    authDomain: 'speech-app-91373.firebaseapp.com',
    storageBucket: 'speech-app-91373.firebasestorage.app',
    measurementId: 'G-XBD9C7SWLJ',
  );
}
